"""server test flag

Revision ID: 177e10e0cf2f
Revises: f61057b65ba3
Create Date: 2026-10-09 17:58:50.893120

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '177e10e0cf2f'
down_revision: str | Sequence[str] | None = 'f61057b65ba3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('is_test', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'is_test')
    # ### end Alembic commands ###
