"""launch

Revision ID: 6e0cc718a467
Revises: 18317d736575
Create Date: 2026-10-09 19:35:48.242625

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6e0cc718a467'
down_revision: str | Sequence[str] | None = '18317d736575'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('launched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('server_seat', sa.Column('setup_done_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_seat', 'setup_done_at')
    op.drop_column('server', 'launched_at')
    # ### end Alembic commands ###
