"""setup assignments

Revision ID: 6e3e6c0ad07c
Revises: 177e10e0cf2f
Create Date: 2026-10-09 18:44:44.232051

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6e3e6c0ad07c'
down_revision: str | Sequence[str] | None = '177e10e0cf2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setup_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_seat_id', sa.Integer(), nullable=False),
    sa.Column('subject_seat_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(length=20), nullable=False),
    sa.Column('based_on_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_seat_id'], ['server_seat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['based_on_id'], ['setup_assignment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_seat_id'], ['server_seat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_seat_id', 'prompt')
    )
    op.add_column('server', sa.Column('setup_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'setup_started_at')
    op.drop_table('setup_assignment')
    # ### end Alembic commands ###
