"""fights

Revision ID: 7d7e5af3d1f8
Revises: d7e308d7bf76
Create Date: 2026-10-09 22:48:49.157406

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7d7e5af3d1f8'
down_revision: str | Sequence[str] | None = 'd7e308d7bf76'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fight',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_seat_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('challenger_id', sa.Uuid(), nullable=False),
    sa.Column('by_chance', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenger_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_seat_id'], ['server_seat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_seat_id', 'day')
    )
    op.create_table('fighter',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fight_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('upgrades', sa.String(length=100), nullable=False),
    sa.Column('element', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fight_id'], ['fight.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fight_id', 'character_id'),
    sa.UniqueConstraint('fight_id', 'position')
    )
    op.create_table('vote',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fight_id', sa.Uuid(), nullable=False),
    sa.Column('voter_seat_id', sa.Uuid(), nullable=False),
    sa.Column('fighters_win', sa.Boolean(), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fight_id'], ['fight.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_seat_id'], ['server_seat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fight_id', 'voter_seat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('fighter')
    op.drop_table('fight')
    # ### end Alembic commands ###
