"""cancelled servers

Revision ID: 9e12c3950a88
Revises: adaa775fa89f
Create Date: 2026-10-10 05:46:07.029398

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9e12c3950a88'
down_revision: str | Sequence[str] | None = 'adaa775fa89f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('server', sa.Column('cancelled_by', sa.Text(), nullable=True))
    op.add_column('server_seat', sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_seat', 'dismissed_at')
    op.drop_column('server', 'cancelled_by')
    op.drop_column('server', 'cancelled_at')
    # ### end Alembic commands ###
