"""hurries

Revision ID: adaa775fa89f
Revises: 7d7e5af3d1f8
Create Date: 2026-10-10 05:35:09.779282

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'adaa775fa89f'
down_revision: str | Sequence[str] | None = '7d7e5af3d1f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hurry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_seat_id', sa.Uuid(), nullable=False),
    sa.Column('target_seat_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('at_fraction', sa.Float(), nullable=False),
    sa.Column('cut_seconds', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sender_seat_id'], ['server_seat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_seat_id'], ['server_seat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_seat_id', 'day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hurry')
    # ### end Alembic commands ###
