"""daily loop

Revision ID: d7e308d7bf76
Revises: b9486f5c3859
Create Date: 2026-10-09 22:31:55.600634

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd7e308d7bf76'
down_revision: str | Sequence[str] | None = 'b9486f5c3859'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenger_prompt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_seat_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('subject_seat_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_seat_id'], ['server_seat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_seat_id'], ['server_seat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_seat_id', 'day')
    )
    op.create_table('day_end',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seat_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seat_id'], ['server_seat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seat_id', 'day')
    )
    op.add_column('character', sa.Column('day', sa.Integer(), nullable=True))
    op.add_column('character', sa.Column('theme', sa.String(length=20), nullable=True))
    op.create_unique_constraint('character_artist_seat_id_day_key', 'character', ['artist_seat_id', 'day'])
    op.add_column('server', sa.Column('test_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'test_day')
    op.drop_constraint('character_artist_seat_id_day_key', 'character', type_='unique')
    op.drop_column('character', 'theme')
    op.drop_column('character', 'day')
    op.drop_table('day_end')
    op.drop_table('challenger_prompt')
    # ### end Alembic commands ###
