"""Challenger titles used when nobody wrote the prompt for a day."""

from app.rules import Theme

PREMADE_PROMPTS = {
    Theme.FOREST: (
        "Keeper of the Ancient Oak",
        "The Mushroom Whisperer",
        "Lost Since Last Summer",
        "Friend of Every Squirrel",
        "The Moss-Covered Wanderer",
        "Ruler of the Fairy Ring",
        "The Hermit Who Bakes Too Much",
        "Wolf Pack Leader",
        "Guardian of the Hidden Path",
        "The Owl's Apprentice",
        "Lumberjack With a Conscience",
        "Collector of Pine Cones",
    ),
    Theme.BEACH: (
        "Sunburnt but Unbothered",
        "The Sandcastle Architect",
        "Champion of Beach Volleyball",
        "Lifeguard on Their Day Off",
        "Ice Cream Smuggler",
        "The Seagull Negotiator",
        "Surf Legend of the Bay",
        "Collector of Odd Shells",
        "Captain of the Inflatable Fleet",
        "The Tan Line Perfectionist",
        "Treasure Hunter With a Metal Detector",
        "Sunset Photographer",
    ),
    Theme.VOLCANO: (
        "Born in the Lava Lake",
        "The Grill Master Supreme",
        "Collector of Obsidian",
        "Dragon Rider of the Crater",
        "The Ashen Scholar",
        "Fireproof and Proud",
        "Keeper of the Eternal Flame",
        "The Molten Blacksmith",
        "Volcanologist Gone Rogue",
        "Ember Sprite in Disguise",
        "Lord of the Sulfur Springs",
        "The Smoke Signal Expert",
    ),
    Theme.SNOW: (
        "The Yeti's Best Friend",
        "Champion Snowball Thrower",
        "Frostbitten Explorer",
        "The Ice Sculptor",
        "Master of the Ski Jump",
        "Hot Cocoa Hoarder",
        "Queen or King of the Glacier",
        "The Avalanche Survivor",
        "Penguin Whisperer",
        "The Igloo Architect",
        "Mountain Rescue Hero",
        "Wearer of Seven Scarves",
    ),
    Theme.SPACE: (
        "First Tourist on Mars",
        "The Alien Ambassador",
        "Captain of a Tiny Spaceship",
        "Lost in the Asteroid Belt",
        "The Moon Gardener",
        "Star Map Cartographer",
        "Zero-Gravity Chef",
        "The Black Hole Survivor",
        "Robot Repair Genius",
        "Comet Chaser",
        "The Intergalactic Postman",
        "Saturn's Ring Skater",
    ),
    Theme.CASTLE: (
        "The Reluctant Heir",
        "Royal Taste Tester",
        "Knight of the Round Snack Table",
        "The Court Jester's Rival",
        "Dragon Negotiator to the Crown",
        "Keeper of the Royal Keys",
        "The Banished Prince or Princess",
        "Master of the Grand Ball",
        "The Castle Ghost",
        "Royal Portrait Painter",
        "Commander of the Moat",
        "The Throne Room Gossip",
    ),
}
